In [14]:
import pandas as pd
import numpy as np

# Dataset Loading

In [15]:
df = pd.read_csv("Salary Data.csv")

print("Shape of Dataset:", df.shape)
df.head()

Shape of Dataset: (10, 5)

   ID  Age  Gender  Salary  Experience
0   1   22    Male   30000           1
1   2   25  Female   35000           2
2   3   28    Male   40000           4
3   4   30  Female   45000           5
4   5   35    Male   50000           8

# Understanding Dataset

In [16]:
print(df.columns)

print("\nData Types:")
print(df.dtypes)

print("\nDataset Info:")
df.info()

Index(['ID', 'Age', 'Gender', 'Salary', 'Experience'], dtype='str')

Data Types:
ID            int64
Age           int64
Gender          str
Salary        int64
Experience    int64
dtype: object

Dataset Info:
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Age         10 non-null     int64
 2   Gender      10 non-null     str
 3   Salary      10 non-null     int64
 4   Experience  10 non-null     int64
dtypes: int64(4), str(1)
memory usage: 532.0 bytes

# Missing Value Handling

In [17]:
print(df.isnull().sum())

df.fillna(df.mean(numeric_only=True), inplace=True)

print("\nAfter Handling Missing Values")
print(df.isnull().sum())

ID            0
Age           0
Gender        0
Salary        0
Experience    0
dtype: int64

After Handling Missing Values
ID            0
Age           0
Gender        0
Salary        0
Experience    0
dtype: int64

# Duplicate Removal

In [18]:
print("Before:", df.shape)

df.drop_duplicates(inplace=True)

print("After:", df.shape)

Before: (10, 5)
After: (10, 5)

# Outlier Detection

In [19]:
numeric_cols = df.select_dtypes(include=['number']).columns

Q1 = df[numeric_cols].quantile(0.25)
Q3 = df[numeric_cols].quantile(0.75)

IQR = Q3 - Q1

df = df[~((df[numeric_cols] < (Q1 - 1.5 * IQR)) |
          (df[numeric_cols] > (Q3 + 1.5 * IQR))).any(axis=1)]

print(df.shape)

(10, 5)

# Data Type Correction

In [20]:
df["Age"] = df["Age"].astype(int)

# Categorical Encoding

In [21]:
categorical_cols = df.select_dtypes(include=['object']).columns

df = pd.get_dummies(df,
                    columns=categorical_cols,
                    drop_first=True)

df.head()

/tmp/ipykernel_11321/2248494761.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=['object']).columns

   ID  Age  Salary  Experience  Gender_Male
0   1   22   30000           1         True
1   2   25   35000           2        False
2   3   28   40000           4         True
3   4   30   45000           5        False
4   5   35   50000           8         True

# Feature Scaling

In [23]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

numeric_cols = df.select_dtypes(include=['number']).columns

df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

df.head()

         ID       Age    Salary  Experience  Gender_Male
0 -1.566699 -1.537729 -1.633587   -1.470294         True
1 -1.218544 -0.988540 -1.058381   -1.120224        False
2 -0.870388 -0.439351 -0.483174   -0.420084         True
3 -0.522233 -0.073225  0.092033   -0.070014        False
4 -0.174078  0.842090  0.667240    0.980196         True

# Removing Irrelevant Features

In [25]:
# Example

df.drop(columns=["Age"], inplace=True)

print(df.columns)

Index(['ID', 'Salary', 'Experience', 'Gender_Male'], dtype='str')

# Skewness Handling

In [26]:
print(df.skew(numeric_only=True))

ID             5.266250e-17
Salary         2.629794e-01
Experience     3.406524e-01
Gender_Male    0.000000e+00
dtype: float64

# Save Cleaned Dataset

In [27]:
df.to_csv("cleaned_dataset.csv", index=False)

print("Dataset Saved Successfully")

Dataset Saved Successfully